services:
  bookkeeper:
    image: registry.gitlab.com/mushr00m/bookkeeper
    ports:
      - 8080:8080
    volumes:
      # BookKeeper.db:
      - ./backend/BookKeeper.db:/app/BookKeeper.db
volumes:
  BookKeeper.db:
    external: true
