services:
  FinancialRecord-Backend:
    image: registry.gitlab.com/financialrecord/backend
    ports:
      - 4000:80
    volumes:
      - ./FinancialRecord.db:/app/FinancialRecord.db
volumes:
  FinancialRecord.db:
    external: true
