services:
  FinancialRecord-Backend:
    image: registry.gitlab.com/financialrecord/backend
    ports:
      - 4000:4000
    volumes:
      - /app/FinancialRecord/FinancialRecord.db:/app/FinancialRecord.db
    networks:
      - app
networks:
  app:
    external: true
