services:
  FinancialRecord-Backend:
    image: registry.gitlab.com/financialrecord/backend
    ports:
      - 4000:80
    volumes:
      - /app/FinancialRecord/FinancialRecord.db:/app/FinancialRecord.db
